networks:
  default:
    external:
      name: roboshop
services:
  # docker run -d -p X:Y --name z --network=A imagename:tag
  mongodb:
    image: mongodb:1
    # networks:
    #   - roboshop

  catalogue:
    image: catalogue:1
    # networks:
    #   - roboshop
    depends_on:
      - mongodb

  web:
    image: web:1
    ports:
      - "80:80"
    depends_on:
      - catalogue
